# Site Settings
title: Anupam Samanta
url: 'http://samanta-anupam.github.io'
baseurl: "" #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Anupam Samanta
tagline: CS Graduate Student at Stony Brook University
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Pursuing Master in Computer Science in Stony Brook University. Enthused by Artificial Neural Network, Big Data, Multimedia systems and/or General Software Development'

#sidebar links
# email: samanta.anupam.19@gmail.com
# phone: #123 432 122
# website: blog.webjeda.com #do not add http://
linkedin: anupam-samanta
github: samanta-anupam
# twitter: #'@anup191291'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
